name: Playwright Tests
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      workersAmount:
        description: 'Workers'
        required: true
        default: 5
      tags:
        description: 'Tags to run tests scenarios'
      choice:
        type: choice
        description: What browser to run tests via
        options:
        - all
        - webkit
        - chromium
        - firefox
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Run Playwright tests
      run: npx playwright test --browser=${{ github.event.inputs.choice }} --config=prod.config.ts --workers=${{ github.event.inputs.workersAmount }} --grep=${{ github.event.inputs.tags }}
