name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
      tags:
        description: 'Tags to run tests scenarios'
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Run Playwright tests
      run: npx playwright test --browser=firefox --config=prod.config.ts --workers=5 --grep=${{ github.event.inputs.tags }} --loglevel=${{ github.event.inputs.logLevel }}
